// This file is auto-generated by @hey-api/openapi-ts

export type Mediflow_DTOs_ChargeableServices_ChargeableServiceDto = {
    name?: (string) | null;
    description?: (string) | null;
    price?: number;
    type?: Mediflow_Entities_ChargeableServices_ChargeableServiceType;
    remark?: (string) | null;
    isActive?: boolean;
};

export type Mediflow_DTOs_ChargeableServices_CreateUpdateChargeableServiceDto = {
    id?: (string) | null;
    name?: (string) | null;
    description?: (string) | null;
    price?: number;
    type?: Mediflow_Entities_ChargeableServices_ChargeableServiceType;
    remark?: (string) | null;
    isActive?: boolean;
};

export type Mediflow_DTOs_Common_AddressDetailsDto = {
    street?: (string) | null;
    city?: (string) | null;
    state?: (string) | null;
    country?: (string) | null;
    postalCode?: (string) | null;
};

export type Mediflow_DTOs_Doctors_CreateUpdateDoctorDto = {
    id?: string;
    firstName: string;
    lastName: string;
    mmcNumber?: (string) | null;
    nationalId?: (string) | null;
    birthDate?: (string) | null;
    gender?: Mediflow_Enums_Gender;
    contactNumber?: (string) | null;
    joinDate?: (string) | null;
    isActive?: boolean;
    userName?: (string) | null;
    newPassword?: (string) | null;
    currentPassword?: (string) | null;
    permissions?: Mediflow_DTOs_Doctors_PermissionAssignmentBatchDto;
};

export type Mediflow_DTOs_Doctors_DoctorDto = {
    id?: string;
    firstName?: (string) | null;
    lastName?: (string) | null;
    mmcNumber?: (string) | null;
    nationalId?: (string) | null;
    birthDate?: string;
    gender?: Mediflow_Enums_Gender;
    isActive?: boolean;
    concurrencyStamp?: (string) | null;
    isOnDuty?: boolean;
};

export type Mediflow_DTOs_Doctors_DoctorListItemDto = {
    id?: string;
    firstName?: (string) | null;
    lastName?: (string) | null;
    mmcNumber?: (string) | null;
    nationalId?: (string) | null;
    birthDate?: string;
    gender?: Mediflow_Enums_Gender;
    isActive?: boolean;
    username?: (string) | null;
};

export type Mediflow_DTOs_Doctors_PermissionAssignmentBatchDto = {
    permissions?: Array<Mediflow_DTOs_Doctors_PermissionAssignmentDto> | null;
};

export type Mediflow_DTOs_Doctors_PermissionAssignmentDto = {
    permission?: (string) | null;
    assigned?: boolean;
};

export type Mediflow_DTOs_Doctors_PermissionTreeNodeDto = {
    text?: (string) | null;
    children?: Array<Mediflow_DTOs_Doctors_PermissionTreeNodeDto> | null;
};

export type Mediflow_DTOs_DocumentTemplates_CreateUpdateDocumentTemplateDto = {
    templateName?: (string) | null;
    templateType?: Mediflow_Entities_DocumentTemplates_TemplateType;
    htmlContent?: (string) | null;
};

export type Mediflow_DTOs_DocumentTemplates_DocumentTemplateDto = {
    id?: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    name?: (string) | null;
    htmlContent?: (string) | null;
};

export type Mediflow_DTOs_Documents_CreateUpdateDocumentDto = {
    id?: string;
    name?: (string) | null;
    htmlContent?: (string) | null;
    type?: Mediflow_Entities_Documents_DocumentType;
    externalBlobId?: (string) | null;
    patientId?: (string) | null;
    patientQueueId?: (string) | null;
    patientSessionId?: (string) | null;
    fileName?: (string) | null;
    fileContentType?: (string) | null;
    fileContentLength?: (number) | null;
};

export type Mediflow_DTOs_Documents_DocumentDto = {
    id?: string;
    creatorId?: string;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    name?: (string) | null;
    htmlContent?: (string) | null;
    type?: Mediflow_Entities_Documents_DocumentType;
    externalBlobId?: (string) | null;
    creationTime?: string;
};

export type Mediflow_DTOs_ExternalBlobs_ExternalBlobDto = {
    id?: string;
    fileSize?: number;
    fileUrl?: (string) | null;
    mimeType?: (string) | null;
};

export type Mediflow_DTOs_FieldTemplates_CreateUpdateFieldTemplateDto = {
    id?: string;
    name?: (string) | null;
    description?: (string) | null;
    fieldName?: (string) | null;
    fieldType?: Mediflow_Entities_FieldTemplates_FieldType;
    fieldValue?: (string) | null;
    isOutdated?: boolean;
};

export type Mediflow_DTOs_FieldTemplates_FieldTemplateDto = {
    id?: string;
    name?: (string) | null;
    description?: (string) | null;
    fieldName?: (string) | null;
    fieldType?: Mediflow_Entities_FieldTemplates_FieldType;
    fieldValue?: (string) | null;
    isOutdated?: boolean;
};

export type Mediflow_DTOs_InsurancePanels_CreateUpdateInsurancePanelDto = {
    id?: (string) | null;
    name?: (string) | null;
    referenceCode?: (string) | null;
    description?: (string) | null;
    address?: (string) | null;
    phoneNumber?: (string) | null;
    email?: (string) | null;
    website?: (string) | null;
    contactPerson?: (string) | null;
    contactPersonPhoneNumber?: (string) | null;
    contactPersonEmail?: (string) | null;
    isActive?: boolean;
};

export type Mediflow_DTOs_InsurancePanels_InsurancePanelDto = {
    id?: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    name?: (string) | null;
    referenceCode?: (string) | null;
    description?: (string) | null;
    address?: (string) | null;
    phoneNumber?: (string) | null;
    email?: (string) | null;
    website?: (string) | null;
    contactPerson?: (string) | null;
    contactPersonPhoneNumber?: (string) | null;
    contactPersonEmail?: (string) | null;
    isActive?: boolean;
};

export type Mediflow_DTOs_InvoiceItems_InvoiceItemDto = {
    id?: string;
    name?: (string) | null;
    type?: Mediflow_Entities_InvoiceItems_InvoiceItemType;
    description?: (string) | null;
    quantity?: number;
    price?: number;
    total?: number;
    notes?: (string) | null;
    invoiceID?: string;
};

export type Mediflow_DTOs_Invoices_CreateUpdateInvoiceDto = {
    invoiceDate?: string;
    invoiceNumber?: (string) | null;
    status?: Mediflow_Entities_Invoices_InvoiceStatus;
    totalAmount?: number;
    paidAmount?: number;
    balanceAmount?: number;
    paymentDueDate?: (string) | null;
    notes?: (string) | null;
    items?: Array<Mediflow_DTOs_InvoiceItems_InvoiceItemDto> | null;
    patientId?: string;
    createUpdatePaymentDtos?: Array<Mediflow_DTOs_Payments_CreateUpdatePaymentDto> | null;
    paymentIdsForDelete?: Array<(string)> | null;
};

export type Mediflow_DTOs_Invoices_InvoiceDto = {
    id?: string;
    invoiceDate?: string;
    invoiceNumber?: (string) | null;
    status?: Mediflow_Entities_Invoices_InvoiceStatus;
    totalAmount?: number;
    paidAmount?: number;
    balanceAmount?: number;
    paymentDueDate?: (string) | null;
    notes?: (string) | null;
    items?: Array<Mediflow_DTOs_InvoiceItems_InvoiceItemDto> | null;
    patientId?: string;
    patient?: Mediflow_DTOs_Patient_PatientDto;
    insurancePanel?: Mediflow_DTOs_InsurancePanels_InsurancePanelDto;
    insurancePanelId?: (string) | null;
    payments?: Array<Mediflow_DTOs_Payments_CreateUpdatePaymentDto> | null;
    visitType?: (string) | null;
    doctorName?: (string) | null;
    invoiceType?: Mediflow_Entities_Invoices_InvoiceType;
};

export type Mediflow_DTOs_MedicalConsentForms_MedicalConsentFormDto = {
    patientName?: (string) | null;
    nationalId?: (string) | null;
    birthDate?: string;
    gender?: Mediflow_Enums_Gender;
    phoneNumber?: (string) | null;
    parentGuardianName?: (string) | null;
    medicalInformation?: Mediflow_DTOs_MedicalConsentForms_MedicalInformationDto;
    consentFormObjectId?: string;
};

export type Mediflow_DTOs_MedicalConsentForms_MedicalInformationDto = {
    hasDisability?: boolean;
    disabilityDetails?: (string) | null;
    hasMedicalConditions?: boolean;
    medicalConditionDetails?: (string) | null;
    hasAllergies?: boolean;
    allergyDetails?: (string) | null;
};

export type Mediflow_DTOs_MedicalHistory_CreateUpdateMedicalHistoryDto = {
    id?: string;
    patientId: string;
    patientQueueId?: (string) | null;
    patientSessionId?: (string) | null;
    symptoms?: (string) | null;
    note?: (string) | null;
    allergies?: (string) | null;
    medicalHistoryPrescriptionItems?: Array<Mediflow_DTOs_MedicalHistoryPrescriptionItems_MedicalHistoryPrescriptionItemDto> | null;
    chargeableServices?: Array<Mediflow_DTOs_ChargeableServices_ChargeableServiceDto> | null;
    medicalSupplies?: Array<Mediflow_DTOs_MedicalSupplies_MedicalSupplyDto> | null;
};

export type Mediflow_DTOs_MedicalHistory_MedicalHistoryDto = {
    id?: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    patientId?: string;
    patientQueueId?: (string) | null;
    symptoms?: (string) | null;
    note?: (string) | null;
    allergies?: (string) | null;
    invoiceNumber?: (string) | null;
};

export type Mediflow_DTOs_MedicalHistory_MedicalHistoryTabItemDto = {
    id?: string;
    date?: string;
    notes?: (string) | null;
    medicines?: Array<Mediflow_DTOs_MedicalHistoryPrescriptionItems_MedicalHistoryPrescriptionItemDto> | null;
    prescriptionId?: (string) | null;
};

export type Mediflow_DTOs_MedicalHistoryPrescriptionItems_MedicalHistoryPrescriptionItemDto = {
    id?: string;
    medicalHistoryId?: string;
    prescriptionId?: (string) | null;
    medicineId?: (string) | null;
    brandName?: (string) | null;
    dosage?: (string) | null;
    frequency?: (string) | null;
    duration?: (string) | null;
    remark?: (string) | null;
    notes?: (string) | null;
    price?: number;
    quantity?: number;
    totalPrice?: number;
};

export type Mediflow_DTOs_MedicalSupplies_CreateUpdateMedicalSupplyDto = {
    id?: string;
    quantity?: number;
    price?: number;
    cost?: number;
    notes?: (string) | null;
    reorderLevel?: (string) | null;
    trackStock?: boolean;
    manufacturer?: (string) | null;
    supplierId?: (string) | null;
    expiryDate?: (string) | null;
    manufactureDate?: (string) | null;
    purchaseDate?: (string) | null;
    arrivalDate?: (string) | null;
    batchNumber?: (string) | null;
    lotNumber?: (string) | null;
    isActive?: boolean;
    name?: (string) | null;
    category?: (string) | null;
};

export type Mediflow_DTOs_MedicalSupplies_MedicalSupplyDto = {
    id?: string;
    quantity?: number;
    price?: number;
    cost?: number;
    notes?: (string) | null;
    reorderLevel?: (string) | null;
    trackStock?: boolean;
    manufacturer?: (string) | null;
    supplierId?: (string) | null;
    expiryDate?: (string) | null;
    manufactureDate?: (string) | null;
    purchaseDate?: (string) | null;
    arrivalDate?: (string) | null;
    batchNumber?: (string) | null;
    lotNumber?: (string) | null;
    isActive?: boolean;
    name?: (string) | null;
    category?: (string) | null;
};

export type Mediflow_DTOs_Medicines_CreateUpdateMedicineDto = {
    quantity?: number;
    price?: number;
    cost?: number;
    notes?: (string) | null;
    reorderLevel?: (string) | null;
    trackStock?: boolean;
    manufacturer?: (string) | null;
    supplierId?: (string) | null;
    expiryDate?: (string) | null;
    manufactureDate?: (string) | null;
    purchaseDate?: (string) | null;
    arrivalDate?: (string) | null;
    batchNumber?: (string) | null;
    lotNumber?: (string) | null;
    isActive?: boolean;
    brandName?: (string) | null;
    genericName?: (string) | null;
    holder?: (string) | null;
    registrationNumber?: (string) | null;
    classification?: Mediflow_Entities_Medicines_MedicineClassification;
    strength?: (string) | null;
    dosageForm?: (string) | null;
    route?: (string) | null;
    frequency?: (string) | null;
    duration?: (string) | null;
};

export type Mediflow_DTOs_Medicines_MedicineDto = {
    id?: string;
    quantity?: number;
    price?: number;
    cost?: number;
    notes?: (string) | null;
    reorderLevel?: (string) | null;
    trackStock?: boolean;
    manufacturer?: (string) | null;
    supplierId?: (string) | null;
    expiryDate?: (string) | null;
    manufactureDate?: (string) | null;
    purchaseDate?: (string) | null;
    arrivalDate?: (string) | null;
    batchNumber?: (string) | null;
    lotNumber?: (string) | null;
    isActive?: boolean;
    brandName?: (string) | null;
    genericName?: (string) | null;
    holder?: (string) | null;
    registrationNumber?: (string) | null;
    classification?: Mediflow_Entities_Medicines_MedicineClassification;
    strength?: (string) | null;
    dosageForm?: (string) | null;
    route?: (string) | null;
    frequency?: (string) | null;
    duration?: (string) | null;
};

export type Mediflow_DTOs_Patient_CreatePatientDto = {
    id?: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    name?: (string) | null;
    identificationType?: Mediflow_Entities_Patients_PatientIdentificationType;
    nationalId?: (string) | null;
    nationalityCode?: (string) | null;
    birthDate?: string;
    gender?: Mediflow_Enums_Gender;
    emailAddress?: (string) | null;
    phoneNumber?: (string) | null;
    address?: Mediflow_DTOs_Common_AddressDetailsDto;
    ethnicity?: (string) | null;
    preferredPaymentType?: Mediflow_Entities_Payments_PaymentType;
    insurancePanelId?: (string) | null;
    medicalConsentForm?: Mediflow_DTOs_MedicalConsentForms_MedicalConsentFormDto;
    consentFormBase64?: (string) | null;
};

export type Mediflow_DTOs_Patient_PatientDto = {
    id?: string;
    name?: (string) | null;
    identificationType?: Mediflow_Entities_Patients_PatientIdentificationType;
    nationalId?: (string) | null;
    nationalityCode?: (string) | null;
    birthDate?: string;
    gender?: Mediflow_Enums_Gender;
    emailAddress?: (string) | null;
    phoneNumber?: (string) | null;
    addressDetails?: Mediflow_DTOs_Common_AddressDetailsDto;
    ethnicity?: (string) | null;
    preferredPaymentId?: string;
    concurrencyStamp?: (string) | null;
    creationTime?: string;
    preferredPaymentType?: Mediflow_Entities_Payments_PaymentType;
    insurancePanelId?: (string) | null;
    hasConsent?: boolean;
    medicalConsentForm?: Mediflow_DTOs_MedicalConsentForms_MedicalConsentFormDto;
};

export type Mediflow_DTOs_Patient_PatientListItemDto = {
    id?: string;
    name?: (string) | null;
    identificationType?: Mediflow_Entities_Patients_PatientIdentificationType;
    nationalId?: (string) | null;
    birthDate?: string;
    gender?: Mediflow_Enums_Gender;
    creationTime?: string;
    latestQueue?: Mediflow_DTOs_PatientQueues_PatientQueueDto;
};

export type Mediflow_DTOs_PatientQueues_AddPatientQueueDto = {
    patientId?: string;
    patientName?: (string) | null;
    nationalId?: (string) | null;
    arrivalTime?: string;
    appointmentTime?: (string) | null;
    isPrioritised?: boolean;
    symptoms?: (string) | null;
    remark?: (string) | null;
    visitType?: (string) | null;
};

export type Mediflow_DTOs_PatientQueues_GenerateMcDto = {
    doctor?: (string) | null;
    patient?: (string) | null;
    startDate?: (string) | null;
    duration?: (string) | null;
    endDate?: (string) | null;
    remarks?: (string) | null;
    date?: (string) | null;
    signature?: (string) | null;
    reason?: (string) | null;
};

export type Mediflow_DTOs_PatientQueues_PatientQueueDto = {
    id?: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    queueNumber?: number;
    patientId?: string;
    patientName?: (string) | null;
    nationalId?: (string) | null;
    arrivalTime?: string;
    appointmentTime?: (string) | null;
    queueTime?: string;
    status?: Mediflow_Entities_PatientQueues_QueueStatus;
    isPrioritised?: boolean;
    patientSessionId?: string;
    remark?: (string) | null;
    elapsedTime?: (string) | null;
    completionTime?: (string) | null;
    visitType?: (string) | null;
    doctorId?: (string) | null;
    invoiceStatus?: Mediflow_Entities_Invoices_InvoiceStatus;
    lastVisitDate?: (string) | null;
    doctorName?: (string) | null;
};

export type Mediflow_DTOs_PatientQueues_PatientQueueWithNotesDto = {
    id?: string;
    queueTime?: string;
    status?: Mediflow_Entities_PatientQueues_QueueStatus;
    elapsedTime?: (string) | null;
    completionTime?: (string) | null;
    visitType?: (string) | null;
    notes?: (string) | null;
};

export type Mediflow_DTOs_PatientSessions_PatientSessionDto = {
    id?: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    patientId?: string;
    startTime?: string;
    endTime?: (string) | null;
    status?: Mediflow_Entities_PatientSessions_PatientSessionStatus;
    queueEntries?: Array<Mediflow_Entities_PatientQueues_PatientQueue> | null;
};

export type Mediflow_DTOs_Payments_CreateUpdatePaymentDto = {
    id?: (string) | null;
    patientId?: string;
    invoiceId?: (string) | null;
    amount?: number;
    paymentType?: Mediflow_Entities_Payments_PaymentType;
    notes?: (string) | null;
    paymentStatus?: Mediflow_Entities_Payments_PaymentStatus;
    paymentDate?: string;
    concurrencyStamp?: (string) | null;
    insurancePanelId?: (string) | null;
    paymentReference?: (string) | null;
};

export type Mediflow_DTOs_Payments_PaymentDto = {
    id?: string;
    patientID?: string;
    invoiceID?: (string) | null;
    amount?: number;
    paymentType?: (string) | null;
    notes?: (string) | null;
    paymentStatus?: Mediflow_Entities_Payments_PaymentStatus;
    paymentDate?: string;
    insurancePanelId?: (string) | null;
    paymentReference?: (string) | null;
};

export type Mediflow_DTOs_Prescriptions_CreateUpdatePrescriptionDto = {
    id?: (string) | null;
    medicineId?: string;
    name?: (string) | null;
    frequency?: (string) | null;
    duration?: (string) | null;
    notes?: (string) | null;
    price?: (string) | null;
    quantity?: (string) | null;
    total?: (string) | null;
};

export type Mediflow_DTOs_Prescriptions_PrescriptionDto = {
    id?: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    prescriptionDate?: string;
    notes?: (string) | null;
    tenantId?: (string) | null;
    prescriptionNumber?: (string) | null;
    patientID?: string;
    documentId?: (string) | null;
    doctorId?: (string) | null;
};

export type Mediflow_DTOs_Reports_AccountsReceivableAgingReportDto = {
    patientName?: (string) | null;
    invoiceNumber?: (string) | null;
    invoiceDate?: string;
    paymentDueDate?: (string) | null;
    totalAmount?: number;
    balanceAmount?: number;
    agingCategory?: (string) | null;
};

export type Mediflow_DTOs_Reports_DailyReportDto = {
    totalInvoices?: number;
    totalBilledAmount?: number;
    totalPaidAmount?: number;
    outstandingBalance?: number;
    services?: Array<Mediflow_DTOs_Reports_ServiceSummaryDto> | null;
    payments?: Array<Mediflow_DTOs_Reports_PaymentSummaryDto> | null;
    unbilledInvoices?: Array<Mediflow_DTOs_Invoices_InvoiceDto> | null;
};

export type Mediflow_DTOs_Reports_PaymentSummaryDto = {
    paymentDate?: string;
    amount?: number;
    paymentType?: (string) | null;
};

export type Mediflow_DTOs_Reports_ServiceSummaryDto = {
    name?: (string) | null;
    quantity?: number;
    total?: number;
};

export type Mediflow_DTOs_ServivceProviders_CreateServiceProviderDto = {
    id?: string;
    name?: (string) | null;
    shortId?: (string) | null;
    contactNumber?: (string) | null;
    email?: (string) | null;
    type?: Mediflow_Entities_ServiceProviders_ServiceProviderType;
    description?: (string) | null;
    businessRegistrationNumber?: (string) | null;
    businessRegistrationType?: (string) | null;
    businessRegistrationCountry?: (string) | null;
    contractStartDate?: (string) | null;
    contractEndDate?: (string) | null;
    isContractActive?: boolean;
    isContractRenewable?: boolean;
    isContractAutoRenewable?: boolean;
    isContractTerminated?: boolean;
    actualStartDate?: (string) | null;
    activationDate?: (string) | null;
    isActive?: boolean;
    address?: Mediflow_DTOs_Common_AddressDetailsDto;
    billingInfo?: Mediflow_Entities_ServiceProviders_BillingInformation;
    hrInfo?: Mediflow_Entities_ServiceProviders_HumanResourcesInformation;
    adminEmail?: (string) | null;
    logoBase64?: (string) | null;
    tenantId?: (string) | null;
};

export type Mediflow_DTOs_ServivceProviders_CreatedServiceProviderDto = {
    id?: string;
    name?: (string) | null;
    adminPassword?: (string) | null;
};

export type Mediflow_DTOs_ServivceProviders_ServiceProviderDto = {
    id?: string;
    name?: (string) | null;
    shortId?: (string) | null;
    contactNumber?: (string) | null;
    email?: (string) | null;
    type?: Mediflow_Entities_ServiceProviders_ServiceProviderType;
    description?: (string) | null;
    businessRegistrationNumber?: (string) | null;
    businessRegistrationType?: (string) | null;
    businessRegistrationCountry?: (string) | null;
    contractStartDate?: (string) | null;
    contractEndDate?: (string) | null;
    isContractActive?: boolean;
    isContractRenewable?: boolean;
    isContractAutoRenewable?: boolean;
    isContractTerminated?: boolean;
    actualStartDate?: (string) | null;
    activationDate?: (string) | null;
    isActive?: boolean;
    address?: Mediflow_DTOs_Common_AddressDetailsDto;
    billingInfo?: Mediflow_Entities_ServiceProviders_BillingInformation;
    hrInfo?: Mediflow_Entities_ServiceProviders_HumanResourcesInformation;
    adminEmail?: (string) | null;
    logoObjectId?: (string) | null;
};

export type Mediflow_DTOs_ServivceProviders_ServiceProviderListItemDto = {
    id?: string;
    name?: (string) | null;
    shortId?: (string) | null;
    type?: Mediflow_Entities_ServiceProviders_ServiceProviderType;
    contactNumber?: (string) | null;
    address?: (string) | null;
    isActive?: boolean;
};

export type Mediflow_DTOs_ServivceProviders_UpdateServiceProviderDto = {
    id?: string;
    name?: (string) | null;
    shortId?: (string) | null;
    contactNumber?: (string) | null;
    email?: (string) | null;
    address?: Mediflow_DTOs_Common_AddressDetailsDto;
    logoBase64?: (string) | null;
    tenantId?: (string) | null;
};

export type Mediflow_DTOs_Staffs_CreateEditStaffDto = {
    firstName?: (string) | null;
    lastName?: (string) | null;
    gender?: Mediflow_Enums_Gender;
    dateOfBirth?: string;
    contactNumber?: (string) | null;
    email?: (string) | null;
    isActive?: boolean;
    joinDate?: string;
    userId?: (string) | null;
    userName?: (string) | null;
    currentPassword?: (string) | null;
    newPassword?: (string) | null;
    permissions?: Mediflow_DTOs_Staffs_PermissionAssignmentBatchDto;
};

export type Mediflow_DTOs_Staffs_PermissionAssignmentBatchDto = {
    permissions?: Array<Mediflow_DTOs_Staffs_PermissionAssignmentDto> | null;
};

export type Mediflow_DTOs_Staffs_PermissionAssignmentDto = {
    permission?: (string) | null;
    assigned?: boolean;
};

export type Mediflow_DTOs_Staffs_PermissionTreeNodeDto = {
    text?: (string) | null;
    children?: Array<Mediflow_DTOs_Staffs_PermissionTreeNodeDto> | null;
};

export type Mediflow_DTOs_Staffs_StaffDto = {
    id?: string;
    firstName?: (string) | null;
    lastName?: (string) | null;
    gender?: Mediflow_Enums_Gender;
    dateOfBirth?: string;
    contactNumber?: (string) | null;
    email?: (string) | null;
    isActive?: boolean;
    joinDate?: string;
    userId?: (string) | null;
};

export type Mediflow_DTOs_Staffs_StaffListItemDto = {
    id?: string;
    firstName?: (string) | null;
    lastName?: (string) | null;
    gender?: Mediflow_Enums_Gender;
    dateOfBirth?: string;
    contactNumber?: (string) | null;
    email?: (string) | null;
    isActive?: boolean;
    joinDate?: string;
    userId?: (string) | null;
    username?: (string) | null;
};

export type Mediflow_DTOs_VisitTemplates_CreateUpdateVisitTemplateDto = {
    id?: (string) | null;
    name?: (string) | null;
    templateConfigs?: Array<Mediflow_DTOs_VisitTemplates_VisitTemplateConfigDto> | null;
};

export type Mediflow_DTOs_VisitTemplates_VisitTemplateConfigDto = {
    diagnosis?: (string) | null;
    notes?: (string) | null;
    medications?: (string) | null;
};

export type Mediflow_DTOs_VisitTemplates_VisitTemplateDto = {
    id?: string;
    name?: (string) | null;
    templateConfigs?: Array<Mediflow_DTOs_VisitTemplates_VisitTemplateConfigDto> | null;
};

export type Mediflow_Entities_ChargeableServices_ChargeableServiceType = 1 | 2 | 3 | 4 | 5 | 6 | 7;

export type Mediflow_Entities_Common_AddressDetails = {
    street?: (string) | null;
    city?: (string) | null;
    state?: (string) | null;
    country?: (string) | null;
    postalCode?: (string) | null;
};

export type Mediflow_Entities_DocumentTemplates_TemplateType = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

export type Mediflow_Entities_Documents_DocumentType = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14;

export type Mediflow_Entities_FieldTemplates_FieldType = 1 | 2;

export type Mediflow_Entities_InvoiceItems_InvoiceItemType = 1 | 2 | 3 | 4;

export type Mediflow_Entities_Invoices_InvoiceStatus = 0 | 1 | 2 | 3 | 4 | 5;

export type Mediflow_Entities_Invoices_InvoiceType = 1 | 2;

export type Mediflow_Entities_MedicalConsentForms_MedicalConsentForm = {
    readonly id?: string;
    readonly creationTime?: string;
    readonly creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    data?: (string) | null;
    consentFormObjectId?: string;
    patientId?: string;
};

export type Mediflow_Entities_Medicines_MedicineClassification = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7;

export type Mediflow_Entities_PatientQueues_PatientQueue = {
    readonly id?: string;
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    concurrencyStamp?: (string) | null;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    queueNumber?: (number) | null;
    patientId?: string;
    patientName?: (string) | null;
    nationalId?: (string) | null;
    arrivalTime?: string;
    appointmentTime?: (string) | null;
    status?: Mediflow_Entities_PatientQueues_QueueStatus;
    isPrioritised?: boolean;
    patientSessionId?: string;
    remark?: (string) | null;
    elapsedTime?: (string) | null;
    completionTime?: (string) | null;
    queueTime?: string;
    visitType?: (string) | null;
    doctorId?: (string) | null;
    tenantId?: (string) | null;
};

export type Mediflow_Entities_PatientQueues_QueueStatus = 1 | 2 | 3 | 4 | 5;

export type Mediflow_Entities_PatientSessions_PatientSessionStatus = 0 | 1 | 2;

export type Mediflow_Entities_Patients_PatientIdentificationType = 0 | 1 | 2;

export type Mediflow_Entities_Payments_PaymentStatus = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export type Mediflow_Entities_Payments_PaymentType = 0 | 1 | 2 | 3 | 4;

export type Mediflow_Entities_ServiceProviders_BillingInformation = {
    address?: Mediflow_Entities_Common_AddressDetails;
    contactNumber?: (string) | null;
    email?: (string) | null;
    taxNumber?: (string) | null;
    taxOffice?: (string) | null;
};

export type Mediflow_Entities_ServiceProviders_HumanResourcesInformation = {
    name?: (string) | null;
    contactNumber?: (string) | null;
    email?: (string) | null;
};

export type Mediflow_Entities_ServiceProviders_ServiceProviderType = 0 | 1 | 2 | 3 | 4;

export type Mediflow_Enums_Gender = 0 | 1 | 2;

export type Volo_Abp_Account_ChangePasswordInput = {
    currentPassword?: (string) | null;
    newPassword: string;
};

export type Volo_Abp_Account_ProfileDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    userName?: (string) | null;
    email?: (string) | null;
    name?: (string) | null;
    surname?: (string) | null;
    phoneNumber?: (string) | null;
    isExternal?: boolean;
    hasPassword?: boolean;
    concurrencyStamp?: (string) | null;
};

export type Volo_Abp_Account_RegisterDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    userName: string;
    emailAddress: string;
    password: string;
    appName: string;
};

export type Volo_Abp_Account_ResetPasswordDto = {
    userId?: string;
    resetToken: string;
    password: string;
};

export type Volo_Abp_Account_SendPasswordResetCodeDto = {
    email: string;
    appName: string;
    returnUrl?: (string) | null;
    returnUrlHash?: (string) | null;
};

export type Volo_Abp_Account_UpdateProfileDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    userName?: (string) | null;
    email?: (string) | null;
    name?: (string) | null;
    surname?: (string) | null;
    phoneNumber?: (string) | null;
    concurrencyStamp?: (string) | null;
};

export type Volo_Abp_Account_VerifyPasswordResetTokenInput = {
    userId?: string;
    resetToken: string;
};

export type Volo_Abp_Account_Web_Areas_Account_Controllers_Models_AbpLoginResult = {
    result?: Volo_Abp_Account_Web_Areas_Account_Controllers_Models_LoginResultType;
    readonly description?: (string) | null;
};

export type Volo_Abp_Account_Web_Areas_Account_Controllers_Models_LoginResultType = 1 | 2 | 3 | 4 | 5;

export type Volo_Abp_Account_Web_Areas_Account_Controllers_Models_UserLoginInfo = {
    userNameOrEmailAddress: string;
    password: string;
    rememberMe?: boolean;
};

export type Volo_Abp_Application_Dtos_ListResultDto_1__Volo_Abp_Identity_IdentityRoleDto__Volo_Abp_Identity_Application_Contracts__Version_8_0_3_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<Volo_Abp_Identity_IdentityRoleDto> | null;
};

export type Volo_Abp_Application_Dtos_ListResultDto_1__Volo_Abp_Users_UserData__Volo_Abp_Users_Abstractions__Version_8_0_3_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<Volo_Abp_Users_UserData> | null;
};

export type Volo_Abp_Application_Dtos_PagedResultDto_1__Mediflow_DTOs_ChargeableServices_ChargeableServiceDto__Mediflow_Application_Contracts__Version_1_0_0_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<Mediflow_DTOs_ChargeableServices_ChargeableServiceDto> | null;
    totalCount?: number;
};

export type Volo_Abp_Application_Dtos_PagedResultDto_1__Mediflow_DTOs_InsurancePanels_InsurancePanelDto__Mediflow_Application_Contracts__Version_1_0_0_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<Mediflow_DTOs_InsurancePanels_InsurancePanelDto> | null;
    totalCount?: number;
};

export type Volo_Abp_Application_Dtos_PagedResultDto_1__Mediflow_DTOs_Invoices_InvoiceDto__Mediflow_Application_Contracts__Version_1_0_0_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<Mediflow_DTOs_Invoices_InvoiceDto> | null;
    totalCount?: number;
};

export type Volo_Abp_Application_Dtos_PagedResultDto_1__Mediflow_DTOs_MedicalSupplies_MedicalSupplyDto__Mediflow_Application_Contracts__Version_1_0_0_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<Mediflow_DTOs_MedicalSupplies_MedicalSupplyDto> | null;
    totalCount?: number;
};

export type Volo_Abp_Application_Dtos_PagedResultDto_1__Mediflow_DTOs_Medicines_MedicineDto__Mediflow_Application_Contracts__Version_1_0_0_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<Mediflow_DTOs_Medicines_MedicineDto> | null;
    totalCount?: number;
};

export type Volo_Abp_Application_Dtos_PagedResultDto_1__Mediflow_DTOs_Patient_PatientListItemDto__Mediflow_Application_Contracts__Version_1_0_0_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<Mediflow_DTOs_Patient_PatientListItemDto> | null;
    totalCount?: number;
};

export type Volo_Abp_Application_Dtos_PagedResultDto_1__Volo_Abp_Identity_IdentityRoleDto__Volo_Abp_Identity_Application_Contracts__Version_8_0_3_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<Volo_Abp_Identity_IdentityRoleDto> | null;
    totalCount?: number;
};

export type Volo_Abp_Application_Dtos_PagedResultDto_1__Volo_Abp_Identity_IdentityUserDto__Volo_Abp_Identity_Application_Contracts__Version_8_0_3_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<Volo_Abp_Identity_IdentityUserDto> | null;
    totalCount?: number;
};

export type Volo_Abp_Application_Dtos_PagedResultDto_1__Volo_Abp_TenantManagement_TenantDto__Volo_Abp_TenantManagement_Application_Contracts__Version_8_0_3_0__Culture_neutral__PublicKeyToken_null__ = {
    items?: Array<Volo_Abp_TenantManagement_TenantDto> | null;
    totalCount?: number;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationAuthConfigurationDto = {
    grantedPolicies?: {
        [key: string]: (boolean);
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationConfigurationDto = {
    localization?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationConfigurationDto;
    auth?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationAuthConfigurationDto;
    setting?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationSettingConfigurationDto;
    currentUser?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentUserDto;
    features?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationFeatureConfigurationDto;
    globalFeatures?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationGlobalFeatureConfigurationDto;
    multiTenancy?: Volo_Abp_AspNetCore_Mvc_MultiTenancy_MultiTenancyInfoDto;
    currentTenant?: Volo_Abp_AspNetCore_Mvc_MultiTenancy_CurrentTenantDto;
    timing?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimingDto;
    clock?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ClockDto;
    objectExtensions?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ObjectExtensionsDto;
    extraProperties?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationFeatureConfigurationDto = {
    values?: {
        [key: string]: ((string) | null);
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationGlobalFeatureConfigurationDto = {
    enabledFeatures?: Array<(string)> | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationConfigurationDto = {
    values?: {
        [key: string]: {
            [key: string]: (string);
        };
    } | null;
    resources?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationResourceDto;
    } | null;
    languages?: Array<Volo_Abp_Localization_LanguageInfo> | null;
    currentCulture?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentCultureDto;
    defaultResourceName?: (string) | null;
    languagesMap?: {
        [key: string]: Array<Volo_Abp_NameValue>;
    } | null;
    languageFilesMap?: {
        [key: string]: Array<Volo_Abp_NameValue>;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationDto = {
    resources?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationResourceDto;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationResourceDto = {
    texts?: {
        [key: string]: (string);
    } | null;
    baseResources?: Array<(string)> | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationSettingConfigurationDto = {
    values?: {
        [key: string]: ((string) | null);
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ClockDto = {
    kind?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentCultureDto = {
    displayName?: (string) | null;
    englishName?: (string) | null;
    threeLetterIsoLanguageName?: (string) | null;
    twoLetterIsoLanguageName?: (string) | null;
    isRightToLeft?: boolean;
    cultureName?: (string) | null;
    name?: (string) | null;
    nativeName?: (string) | null;
    dateTimeFormat?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_DateTimeFormatDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_CurrentUserDto = {
    isAuthenticated?: boolean;
    id?: (string) | null;
    tenantId?: (string) | null;
    impersonatorUserId?: (string) | null;
    impersonatorTenantId?: (string) | null;
    impersonatorUserName?: (string) | null;
    impersonatorTenantName?: (string) | null;
    userName?: (string) | null;
    name?: (string) | null;
    surName?: (string) | null;
    email?: (string) | null;
    emailVerified?: boolean;
    phoneNumber?: (string) | null;
    phoneNumberVerified?: boolean;
    roles?: Array<(string)> | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_DateTimeFormatDto = {
    calendarAlgorithmType?: (string) | null;
    dateTimeFormatLong?: (string) | null;
    shortDatePattern?: (string) | null;
    fullDateTimePattern?: (string) | null;
    dateSeparator?: (string) | null;
    shortTimePattern?: (string) | null;
    longTimePattern?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_IanaTimeZone = {
    timeZoneName?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_EntityExtensionDto = {
    properties?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyDto;
    } | null;
    configuration?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumDto = {
    fields?: Array<Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumFieldDto> | null;
    localizationResource?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumFieldDto = {
    name?: (string) | null;
    value?: unknown;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiCreateDto = {
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiDto = {
    onGet?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiGetDto;
    onCreate?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiCreateDto;
    onUpdate?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiUpdateDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiGetDto = {
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiUpdateDto = {
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyAttributeDto = {
    typeSimple?: (string) | null;
    config?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyDto = {
    type?: (string) | null;
    typeSimple?: (string) | null;
    displayName?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_LocalizableStringDto;
    api?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyApiDto;
    ui?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiDto;
    attributes?: Array<Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyAttributeDto> | null;
    configuration?: {
        [key: string]: unknown;
    } | null;
    defaultValue?: unknown;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiDto = {
    onTable?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiTableDto;
    onCreateForm?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiFormDto;
    onEditForm?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiFormDto;
    lookup?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiLookupDto;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiFormDto = {
    isVisible?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiLookupDto = {
    url?: (string) | null;
    resultListPropertyName?: (string) | null;
    displayPropertyName?: (string) | null;
    valuePropertyName?: (string) | null;
    filterParamName?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionPropertyUiTableDto = {
    isVisible?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_LocalizableStringDto = {
    name?: (string) | null;
    resource?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ModuleExtensionDto = {
    entities?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_EntityExtensionDto;
    } | null;
    configuration?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ObjectExtensionsDto = {
    modules?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ModuleExtensionDto;
    } | null;
    enums?: {
        [key: string]: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ObjectExtending_ExtensionEnumDto;
    } | null;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimeZone = {
    iana?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_IanaTimeZone;
    windows?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_WindowsTimeZone;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimingDto = {
    timeZone?: Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_TimeZone;
};

export type Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_WindowsTimeZone = {
    timeZoneId?: (string) | null;
};

export type Volo_Abp_AspNetCore_Mvc_MultiTenancy_CurrentTenantDto = {
    id?: (string) | null;
    name?: (string) | null;
    isAvailable?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_MultiTenancy_FindTenantResultDto = {
    success?: boolean;
    tenantId?: (string) | null;
    name?: (string) | null;
    isActive?: boolean;
};

export type Volo_Abp_AspNetCore_Mvc_MultiTenancy_MultiTenancyInfoDto = {
    isEnabled?: boolean;
};

export type Volo_Abp_FeatureManagement_FeatureDto = {
    name?: (string) | null;
    displayName?: (string) | null;
    value?: (string) | null;
    provider?: Volo_Abp_FeatureManagement_FeatureProviderDto;
    description?: (string) | null;
    valueType?: Volo_Abp_Validation_StringValues_IStringValueType;
    depth?: number;
    parentName?: (string) | null;
};

export type Volo_Abp_FeatureManagement_FeatureGroupDto = {
    name?: (string) | null;
    displayName?: (string) | null;
    features?: Array<Volo_Abp_FeatureManagement_FeatureDto> | null;
};

export type Volo_Abp_FeatureManagement_FeatureProviderDto = {
    name?: (string) | null;
    key?: (string) | null;
};

export type Volo_Abp_FeatureManagement_GetFeatureListResultDto = {
    groups?: Array<Volo_Abp_FeatureManagement_FeatureGroupDto> | null;
};

export type Volo_Abp_FeatureManagement_UpdateFeatureDto = {
    name?: (string) | null;
    value?: (string) | null;
};

export type Volo_Abp_FeatureManagement_UpdateFeaturesDto = {
    features?: Array<Volo_Abp_FeatureManagement_UpdateFeatureDto> | null;
};

export type Volo_Abp_Http_Modeling_ActionApiDescriptionModel = {
    uniqueName?: (string) | null;
    name?: (string) | null;
    httpMethod?: (string) | null;
    url?: (string) | null;
    supportedVersions?: Array<(string)> | null;
    parametersOnMethod?: Array<Volo_Abp_Http_Modeling_MethodParameterApiDescriptionModel> | null;
    parameters?: Array<Volo_Abp_Http_Modeling_ParameterApiDescriptionModel> | null;
    returnValue?: Volo_Abp_Http_Modeling_ReturnValueApiDescriptionModel;
    allowAnonymous?: (boolean) | null;
    implementFrom?: (string) | null;
};

export type Volo_Abp_Http_Modeling_ApplicationApiDescriptionModel = {
    modules?: {
        [key: string]: Volo_Abp_Http_Modeling_ModuleApiDescriptionModel;
    } | null;
    types?: {
        [key: string]: Volo_Abp_Http_Modeling_TypeApiDescriptionModel;
    } | null;
};

export type Volo_Abp_Http_Modeling_ControllerApiDescriptionModel = {
    controllerName?: (string) | null;
    controllerGroupName?: (string) | null;
    isRemoteService?: boolean;
    isIntegrationService?: boolean;
    apiVersion?: (string) | null;
    type?: (string) | null;
    interfaces?: Array<Volo_Abp_Http_Modeling_ControllerInterfaceApiDescriptionModel> | null;
    actions?: {
        [key: string]: Volo_Abp_Http_Modeling_ActionApiDescriptionModel;
    } | null;
};

export type Volo_Abp_Http_Modeling_ControllerInterfaceApiDescriptionModel = {
    type?: (string) | null;
    name?: (string) | null;
    methods?: Array<Volo_Abp_Http_Modeling_InterfaceMethodApiDescriptionModel> | null;
};

export type Volo_Abp_Http_Modeling_InterfaceMethodApiDescriptionModel = {
    name?: (string) | null;
    parametersOnMethod?: Array<Volo_Abp_Http_Modeling_MethodParameterApiDescriptionModel> | null;
    returnValue?: Volo_Abp_Http_Modeling_ReturnValueApiDescriptionModel;
};

export type Volo_Abp_Http_Modeling_MethodParameterApiDescriptionModel = {
    name?: (string) | null;
    typeAsString?: (string) | null;
    type?: (string) | null;
    typeSimple?: (string) | null;
    isOptional?: boolean;
    defaultValue?: unknown;
};

export type Volo_Abp_Http_Modeling_ModuleApiDescriptionModel = {
    rootPath?: (string) | null;
    remoteServiceName?: (string) | null;
    controllers?: {
        [key: string]: Volo_Abp_Http_Modeling_ControllerApiDescriptionModel;
    } | null;
};

export type Volo_Abp_Http_Modeling_ParameterApiDescriptionModel = {
    nameOnMethod?: (string) | null;
    name?: (string) | null;
    jsonName?: (string) | null;
    type?: (string) | null;
    typeSimple?: (string) | null;
    isOptional?: boolean;
    defaultValue?: unknown;
    constraintTypes?: Array<(string)> | null;
    bindingSourceId?: (string) | null;
    descriptorName?: (string) | null;
};

export type Volo_Abp_Http_Modeling_PropertyApiDescriptionModel = {
    name?: (string) | null;
    jsonName?: (string) | null;
    type?: (string) | null;
    typeSimple?: (string) | null;
    isRequired?: boolean;
    minLength?: (number) | null;
    maxLength?: (number) | null;
    minimum?: (string) | null;
    maximum?: (string) | null;
    regex?: (string) | null;
};

export type Volo_Abp_Http_Modeling_ReturnValueApiDescriptionModel = {
    type?: (string) | null;
    typeSimple?: (string) | null;
};

export type Volo_Abp_Http_Modeling_TypeApiDescriptionModel = {
    baseType?: (string) | null;
    isEnum?: boolean;
    enumNames?: Array<(string)> | null;
    enumValues?: Array<unknown> | null;
    genericArguments?: Array<(string)> | null;
    properties?: Array<Volo_Abp_Http_Modeling_PropertyApiDescriptionModel> | null;
};

export type Volo_Abp_Http_RemoteServiceErrorInfo = {
    code?: (string) | null;
    message?: (string) | null;
    details?: (string) | null;
    data?: {
        [key: string]: unknown;
    } | null;
    validationErrors?: Array<Volo_Abp_Http_RemoteServiceValidationErrorInfo> | null;
};

export type Volo_Abp_Http_RemoteServiceErrorResponse = {
    error?: Volo_Abp_Http_RemoteServiceErrorInfo;
};

export type Volo_Abp_Http_RemoteServiceValidationErrorInfo = {
    message?: (string) | null;
    members?: Array<(string)> | null;
};

export type Volo_Abp_Identity_IdentityRoleCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    isDefault?: boolean;
    isPublic?: boolean;
};

export type Volo_Abp_Identity_IdentityRoleDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    id?: string;
    name?: (string) | null;
    isDefault?: boolean;
    isStatic?: boolean;
    isPublic?: boolean;
    concurrencyStamp?: (string) | null;
};

export type Volo_Abp_Identity_IdentityRoleUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    isDefault?: boolean;
    isPublic?: boolean;
    concurrencyStamp?: (string) | null;
};

export type Volo_Abp_Identity_IdentityUserCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    userName: string;
    name?: (string) | null;
    surname?: (string) | null;
    email: string;
    phoneNumber?: (string) | null;
    isActive?: boolean;
    lockoutEnabled?: boolean;
    roleNames?: Array<(string)> | null;
    password: string;
};

export type Volo_Abp_Identity_IdentityUserDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    id?: string;
    creationTime?: string;
    creatorId?: (string) | null;
    lastModificationTime?: (string) | null;
    lastModifierId?: (string) | null;
    isDeleted?: boolean;
    deleterId?: (string) | null;
    deletionTime?: (string) | null;
    tenantId?: (string) | null;
    userName?: (string) | null;
    name?: (string) | null;
    surname?: (string) | null;
    email?: (string) | null;
    emailConfirmed?: boolean;
    phoneNumber?: (string) | null;
    phoneNumberConfirmed?: boolean;
    isActive?: boolean;
    lockoutEnabled?: boolean;
    accessFailedCount?: number;
    lockoutEnd?: (string) | null;
    concurrencyStamp?: (string) | null;
    entityVersion?: number;
    lastPasswordChangeTime?: (string) | null;
};

export type Volo_Abp_Identity_IdentityUserUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    userName: string;
    name?: (string) | null;
    surname?: (string) | null;
    email: string;
    phoneNumber?: (string) | null;
    isActive?: boolean;
    lockoutEnabled?: boolean;
    roleNames?: Array<(string)> | null;
    password?: (string) | null;
    concurrencyStamp?: (string) | null;
};

export type Volo_Abp_Identity_IdentityUserUpdateRolesDto = {
    roleNames: Array<(string)>;
};

export type Volo_Abp_Localization_LanguageInfo = {
    cultureName?: (string) | null;
    uiCultureName?: (string) | null;
    displayName?: (string) | null;
    readonly twoLetterISOLanguageName?: (string) | null;
    flagIcon?: (string) | null;
};

export type Volo_Abp_NameValue = {
    name?: (string) | null;
    value?: (string) | null;
};

export type Volo_Abp_PermissionManagement_GetPermissionListResultDto = {
    entityDisplayName?: (string) | null;
    groups?: Array<Volo_Abp_PermissionManagement_PermissionGroupDto> | null;
};

export type Volo_Abp_PermissionManagement_PermissionGrantInfoDto = {
    name?: (string) | null;
    displayName?: (string) | null;
    parentName?: (string) | null;
    isGranted?: boolean;
    allowedProviders?: Array<(string)> | null;
    grantedProviders?: Array<Volo_Abp_PermissionManagement_ProviderInfoDto> | null;
};

export type Volo_Abp_PermissionManagement_PermissionGroupDto = {
    name?: (string) | null;
    displayName?: (string) | null;
    displayNameKey?: (string) | null;
    displayNameResource?: (string) | null;
    permissions?: Array<Volo_Abp_PermissionManagement_PermissionGrantInfoDto> | null;
};

export type Volo_Abp_PermissionManagement_ProviderInfoDto = {
    providerName?: (string) | null;
    providerKey?: (string) | null;
};

export type Volo_Abp_PermissionManagement_UpdatePermissionDto = {
    name?: (string) | null;
    isGranted?: boolean;
};

export type Volo_Abp_PermissionManagement_UpdatePermissionsDto = {
    permissions?: Array<Volo_Abp_PermissionManagement_UpdatePermissionDto> | null;
};

export type Volo_Abp_SettingManagement_EmailSettingsDto = {
    smtpHost?: (string) | null;
    smtpPort?: number;
    smtpUserName?: (string) | null;
    smtpPassword?: (string) | null;
    smtpDomain?: (string) | null;
    smtpEnableSsl?: boolean;
    smtpUseDefaultCredentials?: boolean;
    defaultFromAddress?: (string) | null;
    defaultFromDisplayName?: (string) | null;
};

export type Volo_Abp_SettingManagement_SendTestEmailInput = {
    senderEmailAddress: string;
    targetEmailAddress: string;
    subject: string;
    body?: (string) | null;
};

export type Volo_Abp_SettingManagement_UpdateEmailSettingsDto = {
    smtpHost?: (string) | null;
    smtpPort?: number;
    smtpUserName?: (string) | null;
    smtpPassword?: (string) | null;
    smtpDomain?: (string) | null;
    smtpEnableSsl?: boolean;
    smtpUseDefaultCredentials?: boolean;
    defaultFromAddress: string;
    defaultFromDisplayName: string;
};

export type Volo_Abp_TenantManagement_TenantCreateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    adminEmailAddress: string;
    adminPassword: string;
};

export type Volo_Abp_TenantManagement_TenantDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    id?: string;
    name?: (string) | null;
    concurrencyStamp?: (string) | null;
};

export type Volo_Abp_TenantManagement_TenantUpdateDto = {
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
    name: string;
    concurrencyStamp?: (string) | null;
};

export type Volo_Abp_Users_UserData = {
    id?: string;
    tenantId?: (string) | null;
    userName?: (string) | null;
    name?: (string) | null;
    surname?: (string) | null;
    isActive?: boolean;
    email?: (string) | null;
    emailConfirmed?: boolean;
    phoneNumber?: (string) | null;
    phoneNumberConfirmed?: boolean;
    readonly extraProperties?: {
        [key: string]: unknown;
    } | null;
};

export type Volo_Abp_Validation_StringValues_IStringValueType = {
    readonly name?: (string) | null;
    readonly properties?: {
        [key: string]: unknown;
    } | null;
    validator?: Volo_Abp_Validation_StringValues_IValueValidator;
};

export type Volo_Abp_Validation_StringValues_IValueValidator = {
    readonly name?: (string) | null;
    readonly properties?: {
        [key: string]: unknown;
    } | null;
};

export type GetApiAbpApiDefinitionData = {
    includeTypes?: boolean;
};

export type GetApiAbpApiDefinitionResponse = (Volo_Abp_Http_Modeling_ApplicationApiDescriptionModel);

export type GetApiAbpApplicationConfigurationData = {
    includeLocalizationResources?: boolean;
};

export type GetApiAbpApplicationConfigurationResponse = (Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationConfigurationDto);

export type GetApiAbpApplicationLocalizationData = {
    cultureName: string;
    onlyDynamics?: boolean;
};

export type GetApiAbpApplicationLocalizationResponse = (Volo_Abp_AspNetCore_Mvc_ApplicationConfigurations_ApplicationLocalizationDto);

export type GetApiAbpMultiTenancyTenantsByNameByNameData = {
    name: string;
};

export type GetApiAbpMultiTenancyTenantsByNameByNameResponse = (Volo_Abp_AspNetCore_Mvc_MultiTenancy_FindTenantResultDto);

export type GetApiAbpMultiTenancyTenantsByIdByIdData = {
    id: string;
};

export type GetApiAbpMultiTenancyTenantsByIdByIdResponse = (Volo_Abp_AspNetCore_Mvc_MultiTenancy_FindTenantResultDto);

export type PostApiAccountRegisterData = {
    requestBody?: Volo_Abp_Account_RegisterDto;
};

export type PostApiAccountRegisterResponse = (Volo_Abp_Identity_IdentityUserDto);

export type PostApiAccountSendPasswordResetCodeData = {
    requestBody?: Volo_Abp_Account_SendPasswordResetCodeDto;
};

export type PostApiAccountSendPasswordResetCodeResponse = (unknown);

export type PostApiAccountVerifyPasswordResetTokenData = {
    requestBody?: Volo_Abp_Account_VerifyPasswordResetTokenInput;
};

export type PostApiAccountVerifyPasswordResetTokenResponse = (boolean);

export type PostApiAccountResetPasswordData = {
    requestBody?: Volo_Abp_Account_ResetPasswordDto;
};

export type PostApiAccountResetPasswordResponse = (unknown);

export type PostApiAppChargeableServiceChargeableServiceData = {
    requestBody?: Mediflow_DTOs_ChargeableServices_CreateUpdateChargeableServiceDto;
};

export type PostApiAppChargeableServiceChargeableServiceResponse = (Mediflow_DTOs_ChargeableServices_ChargeableServiceDto);

export type DeleteApiAppChargeableServiceByIdChargeableServiceData = {
    id: string;
};

export type DeleteApiAppChargeableServiceByIdChargeableServiceResponse = (unknown);

export type GetApiAppChargeableServiceByIdChargeableServiceData = {
    id: string;
};

export type GetApiAppChargeableServiceByIdChargeableServiceResponse = (Mediflow_DTOs_ChargeableServices_ChargeableServiceDto);

export type PutApiAppChargeableServiceByIdChargeableServiceData = {
    id: string;
    requestBody?: Mediflow_DTOs_ChargeableServices_CreateUpdateChargeableServiceDto;
};

export type PutApiAppChargeableServiceByIdChargeableServiceResponse = (Mediflow_DTOs_ChargeableServices_ChargeableServiceDto);

export type GetApiAppChargeableServiceChargeableServiceListResponse = (Volo_Abp_Application_Dtos_PagedResultDto_1__Mediflow_DTOs_ChargeableServices_ChargeableServiceDto__Mediflow_Application_Contracts__Version_1_0_0_0__Culture_neutral__PublicKeyToken_null__);

export type GetApiAppDoctorByIdData = {
    id: string;
};

export type GetApiAppDoctorByIdResponse = (Mediflow_DTOs_Doctors_DoctorDto);

export type PutApiAppDoctorByIdData = {
    id: string;
    requestBody?: Mediflow_DTOs_Doctors_CreateUpdateDoctorDto;
};

export type PutApiAppDoctorByIdResponse = (Mediflow_DTOs_Doctors_DoctorDto);

export type GetApiAppDoctorByIdByUserIdData = {
    id: string;
};

export type GetApiAppDoctorByIdByUserIdResponse = (Mediflow_DTOs_Doctors_DoctorDto);

export type GetApiAppDoctorDoctorForEditByDoctorIdData = {
    doctorId: string;
};

export type GetApiAppDoctorDoctorForEditByDoctorIdResponse = (Mediflow_DTOs_Doctors_CreateUpdateDoctorDto);

export type GetApiAppDoctorResponse = (Array<Mediflow_DTOs_Doctors_DoctorDto>);

export type PostApiAppDoctorData = {
    requestBody?: Mediflow_DTOs_Doctors_CreateUpdateDoctorDto;
};

export type PostApiAppDoctorResponse = (Mediflow_DTOs_Doctors_DoctorDto);

export type GetApiAppDoctorDoctorListResponse = (Array<Mediflow_DTOs_Doctors_DoctorListItemDto>);

export type PostApiAppDoctorAssignPermissionsToDoctorByUserIdData = {
    requestBody?: Mediflow_DTOs_Doctors_PermissionAssignmentBatchDto;
    userId: string;
};

export type PostApiAppDoctorAssignPermissionsToDoctorByUserIdResponse = (unknown);

export type GetApiAppDoctorPermissionsResponse = (Mediflow_DTOs_Doctors_PermissionTreeNodeDto);

export type PostApiAppDoctorByIdSetDoctorOnDutyData = {
    id: string;
    isOnDuty?: boolean;
};

export type PostApiAppDoctorByIdSetDoctorOnDutyResponse = (unknown);

export type PutApiAppDoctorByIdDoctorOnDutyData = {
    id: string;
};

export type PutApiAppDoctorByIdDoctorOnDutyResponse = (unknown);

export type GetApiAppDoctorDoctorOnDutyResponse = (Mediflow_DTOs_Doctors_DoctorDto);

export type GetApiAppDocumentByIdDocumentByIdData = {
    id: string;
};

export type GetApiAppDocumentByIdDocumentByIdResponse = (Mediflow_DTOs_Documents_DocumentDto);

export type PostApiAppDocumentGeneratePdfFromDocumentByDocumentIdData = {
    documentId: string;
};

export type PostApiAppDocumentGeneratePdfFromDocumentByDocumentIdResponse = (string);

export type PostApiAppDocumentDocumentData = {
    requestBody?: Mediflow_DTOs_Documents_CreateUpdateDocumentDto;
};

export type PostApiAppDocumentDocumentResponse = (Mediflow_DTOs_Documents_DocumentDto);

export type PutApiAppDocumentByIdDocumentData = {
    id: string;
    requestBody?: Mediflow_DTOs_Documents_CreateUpdateDocumentDto;
};

export type PutApiAppDocumentByIdDocumentResponse = (Mediflow_DTOs_Documents_DocumentDto);

export type GetApiAppDocumentDocumentsByQueueIdByQueueIdData = {
    queueId: string;
};

export type GetApiAppDocumentDocumentsByQueueIdByQueueIdResponse = (Array<Mediflow_DTOs_Documents_DocumentDto>);

export type PostApiAppDocumentTemplateTemplateData = {
    requestBody?: Mediflow_DTOs_DocumentTemplates_CreateUpdateDocumentTemplateDto;
};

export type PostApiAppDocumentTemplateTemplateResponse = (Mediflow_DTOs_DocumentTemplates_DocumentTemplateDto);

export type DeleteApiAppDocumentTemplateByIdTemplateByIdData = {
    id: string;
};

export type DeleteApiAppDocumentTemplateByIdTemplateByIdResponse = (unknown);

export type GetApiAppDocumentTemplateByIdTemplateByIdData = {
    id: string;
};

export type GetApiAppDocumentTemplateByIdTemplateByIdResponse = (Mediflow_DTOs_DocumentTemplates_DocumentTemplateDto);

export type PutApiAppDocumentTemplateByIdTemplateData = {
    id: string;
    requestBody?: Mediflow_DTOs_DocumentTemplates_CreateUpdateDocumentTemplateDto;
};

export type PutApiAppDocumentTemplateByIdTemplateResponse = (Mediflow_DTOs_DocumentTemplates_DocumentTemplateDto);

export type PostApiAccountDynamicClaimsRefreshResponse = (unknown);

export type GetApiSettingManagementEmailingResponse = (Volo_Abp_SettingManagement_EmailSettingsDto);

export type PostApiSettingManagementEmailingData = {
    requestBody?: Volo_Abp_SettingManagement_UpdateEmailSettingsDto;
};

export type PostApiSettingManagementEmailingResponse = (unknown);

export type PostApiSettingManagementEmailingSendTestEmailData = {
    requestBody?: Volo_Abp_SettingManagement_SendTestEmailInput;
};

export type PostApiSettingManagementEmailingSendTestEmailResponse = (unknown);

export type PostApiAppExternalBlobSaveBlobData = {
    formData?: {
        file?: (Blob | File);
    };
};

export type PostApiAppExternalBlobSaveBlobResponse = (Mediflow_DTOs_ExternalBlobs_ExternalBlobDto);

export type PostApiAppExternalBlobByIdDownloadBlobData = {
    id: string;
};

export type PostApiAppExternalBlobByIdDownloadBlobResponse = ((Blob | File));

export type DeleteApiAppExternalBlobByIdBlobData = {
    id: string;
};

export type DeleteApiAppExternalBlobByIdBlobResponse = (unknown);

export type GetApiFeatureManagementFeaturesData = {
    providerKey?: string;
    providerName?: string;
};

export type GetApiFeatureManagementFeaturesResponse = (Volo_Abp_FeatureManagement_GetFeatureListResultDto);

export type PutApiFeatureManagementFeaturesData = {
    providerKey?: string;
    providerName?: string;
    requestBody?: Volo_Abp_FeatureManagement_UpdateFeaturesDto;
};

export type PutApiFeatureManagementFeaturesResponse = (unknown);

export type DeleteApiFeatureManagementFeaturesData = {
    providerKey?: string;
    providerName?: string;
};

export type DeleteApiFeatureManagementFeaturesResponse = (unknown);

export type PostApiAppFieldTemplateFieldTemplateData = {
    requestBody?: Mediflow_DTOs_FieldTemplates_CreateUpdateFieldTemplateDto;
};

export type PostApiAppFieldTemplateFieldTemplateResponse = (Mediflow_DTOs_FieldTemplates_FieldTemplateDto);

export type DeleteApiAppFieldTemplateByIdFieldTemplateData = {
    id: string;
};

export type DeleteApiAppFieldTemplateByIdFieldTemplateResponse = (unknown);

export type GetApiAppFieldTemplateByIdFieldTemplateData = {
    id: string;
};

export type GetApiAppFieldTemplateByIdFieldTemplateResponse = (Mediflow_DTOs_FieldTemplates_FieldTemplateDto);

export type PutApiAppFieldTemplateByIdFieldTemplateData = {
    id: string;
    requestBody?: Mediflow_DTOs_FieldTemplates_CreateUpdateFieldTemplateDto;
};

export type PutApiAppFieldTemplateByIdFieldTemplateResponse = (Mediflow_DTOs_FieldTemplates_FieldTemplateDto);

export type GetApiAppFieldTemplateFieldTemplatesResponse = (Array<Mediflow_DTOs_FieldTemplates_FieldTemplateDto>);

export type PostApiAppInsurancePanelData = {
    requestBody?: Mediflow_DTOs_InsurancePanels_CreateUpdateInsurancePanelDto;
};

export type PostApiAppInsurancePanelResponse = (Mediflow_DTOs_InsurancePanels_InsurancePanelDto);

export type GetApiAppInsurancePanelResponse = (Array<Mediflow_DTOs_InsurancePanels_InsurancePanelDto>);

export type DeleteApiAppInsurancePanelByIdData = {
    id: string;
};

export type DeleteApiAppInsurancePanelByIdResponse = (unknown);

export type GetApiAppInsurancePanelByIdData = {
    id: string;
};

export type GetApiAppInsurancePanelByIdResponse = (Mediflow_DTOs_InsurancePanels_InsurancePanelDto);

export type PutApiAppInsurancePanelByIdData = {
    id: string;
    requestBody?: Mediflow_DTOs_InsurancePanels_CreateUpdateInsurancePanelDto;
};

export type PutApiAppInsurancePanelByIdResponse = (Mediflow_DTOs_InsurancePanels_InsurancePanelDto);

export type GetApiAppInsurancePanelInsurancePanelListResponse = (Volo_Abp_Application_Dtos_PagedResultDto_1__Mediflow_DTOs_InsurancePanels_InsurancePanelDto__Mediflow_Application_Contracts__Version_1_0_0_0__Culture_neutral__PublicKeyToken_null__);

export type PostApiAppInvoiceInvoiceData = {
    requestBody?: Mediflow_DTOs_Invoices_CreateUpdateInvoiceDto;
};

export type PostApiAppInvoiceInvoiceResponse = (Mediflow_DTOs_Invoices_InvoiceDto);

export type GetApiAppInvoiceByIdInvoiceData = {
    id: string;
};

export type GetApiAppInvoiceByIdInvoiceResponse = (Mediflow_DTOs_Invoices_InvoiceDto);

export type PutApiAppInvoiceByIdInvoiceData = {
    id: string;
    requestBody?: Mediflow_DTOs_Invoices_CreateUpdateInvoiceDto;
};

export type PutApiAppInvoiceByIdInvoiceResponse = (Mediflow_DTOs_Invoices_InvoiceDto);

export type GetApiAppInvoiceInvoiceByNumberData = {
    number?: string;
};

export type GetApiAppInvoiceInvoiceByNumberResponse = (Mediflow_DTOs_Invoices_InvoiceDto);

export type GetApiAppInvoiceInvoiceListData = {
    maxResultCount?: number;
    searchTerm?: string;
    skipCount?: number;
    sortDirection?: string;
    sortField?: string;
};

export type GetApiAppInvoiceInvoiceListResponse = (Volo_Abp_Application_Dtos_PagedResultDto_1);

export type GetApiAppInvoicePendingInvoicesResponse = (Array<Mediflow_DTOs_Invoices_InvoiceDto>);

export type PutApiAppInvoiceByIdPanelClaimInvoiceData = {
    id: string;
    requestBody?: Mediflow_DTOs_Invoices_CreateUpdateInvoiceDto;
};

export type PutApiAppInvoiceByIdPanelClaimInvoiceResponse = (Mediflow_DTOs_Invoices_InvoiceDto);

export type PostApiAppInvoiceByIdVoidInvoiceData = {
    id: string;
};

export type PostApiAppInvoiceByIdVoidInvoiceResponse = (Mediflow_DTOs_Invoices_InvoiceDto);

export type GetApiAppInvoiceInvoicesByPatientIdByPatientIdData = {
    patientId: string;
};

export type GetApiAppInvoiceInvoicesByPatientIdByPatientIdResponse = (Array<Mediflow_DTOs_Invoices_InvoiceDto>);

export type GetApiAppInvoicePanelInvoiceListData = {
    maxResultCount?: number;
    searchTerm?: string;
    skipCount?: number;
    sortDirection?: string;
    sortField?: string;
};

export type GetApiAppInvoicePanelInvoiceListResponse = (Volo_Abp_Application_Dtos_PagedResultDto_1);

export type PostApiAccountLoginData = {
    requestBody?: Volo_Abp_Account_Web_Areas_Account_Controllers_Models_UserLoginInfo;
};

export type PostApiAccountLoginResponse = (Volo_Abp_Account_Web_Areas_Account_Controllers_Models_AbpLoginResult);

export type GetApiAccountLogoutResponse = (unknown);

export type PostApiAccountCheckPasswordData = {
    requestBody?: Volo_Abp_Account_Web_Areas_Account_Controllers_Models_UserLoginInfo;
};

export type PostApiAccountCheckPasswordResponse = (Volo_Abp_Account_Web_Areas_Account_Controllers_Models_AbpLoginResult);

export type PostApiAppMedicalConsentFormData = {
    requestBody?: Mediflow_DTOs_MedicalConsentForms_MedicalConsentFormDto;
};

export type PostApiAppMedicalConsentFormResponse = (Mediflow_Entities_MedicalConsentForms_MedicalConsentForm);

export type DeleteApiAppMedicalConsentFormByIdData = {
    id: string;
};

export type DeleteApiAppMedicalConsentFormByIdResponse = (unknown);

export type GetApiAppMedicalConsentFormByIdData = {
    id: string;
};

export type GetApiAppMedicalConsentFormByIdResponse = (Mediflow_DTOs_MedicalConsentForms_MedicalConsentFormDto);

export type PutApiAppMedicalConsentFormByIdData = {
    id: string;
    requestBody?: Mediflow_DTOs_MedicalConsentForms_MedicalConsentFormDto;
};

export type PutApiAppMedicalConsentFormByIdResponse = (unknown);

export type GetApiAppMedicalConsentFormByIdByPatientIdData = {
    id: string;
};

export type GetApiAppMedicalConsentFormByIdByPatientIdResponse = (Mediflow_DTOs_MedicalConsentForms_MedicalConsentFormDto);

export type PostApiAppMedicalHistoryUpdateMedicalHistoryData = {
    requestBody?: Mediflow_DTOs_MedicalHistory_CreateUpdateMedicalHistoryDto;
};

export type PostApiAppMedicalHistoryUpdateMedicalHistoryResponse = (Mediflow_DTOs_MedicalHistory_MedicalHistoryDto);

export type DeleteApiAppMedicalHistoryByIdMedicalHistoryData = {
    id: string;
};

export type DeleteApiAppMedicalHistoryByIdMedicalHistoryResponse = (unknown);

export type GetApiAppMedicalHistoryByIdMedicalHistoryData = {
    id: string;
};

export type GetApiAppMedicalHistoryByIdMedicalHistoryResponse = (Mediflow_DTOs_MedicalHistory_MedicalHistoryDto);

export type PutApiAppMedicalHistoryByIdMedicalHistoryData = {
    id: string;
    requestBody?: Mediflow_DTOs_MedicalHistory_CreateUpdateMedicalHistoryDto;
};

export type PutApiAppMedicalHistoryByIdMedicalHistoryResponse = (Mediflow_DTOs_MedicalHistory_MedicalHistoryDto);

export type GetApiAppMedicalHistoryMedicalHistoryByQueueIdByQueueIdData = {
    queueId: string;
};

export type GetApiAppMedicalHistoryMedicalHistoryByQueueIdByQueueIdResponse = (Mediflow_DTOs_MedicalHistory_MedicalHistoryDto);

export type GetApiAppMedicalHistoryMedicalHistoryListByQueueIdsData = {
    queueIds?: Array<(string)>;
};

export type GetApiAppMedicalHistoryMedicalHistoryListByQueueIdsResponse = (Array<Mediflow_DTOs_MedicalHistory_MedicalHistoryDto>);

export type GetApiAppMedicalHistoryMedicalHistoryListByPatientIdData = {
    date?: string;
    patientId: string;
};

export type GetApiAppMedicalHistoryMedicalHistoryListByPatientIdResponse = (Array<Mediflow_DTOs_MedicalHistory_MedicalHistoryDto>);

export type GetApiAppMedicalHistoryMedicalHistoryTabItemsByPatientIdData = {
    patientId: string;
};

export type GetApiAppMedicalHistoryMedicalHistoryTabItemsByPatientIdResponse = (Array<Mediflow_DTOs_MedicalHistory_MedicalHistoryTabItemDto>);

export type PostApiAppMedicalSupplyMedicalSupplyData = {
    requestBody?: Mediflow_DTOs_MedicalSupplies_CreateUpdateMedicalSupplyDto;
};

export type PostApiAppMedicalSupplyMedicalSupplyResponse = (Mediflow_DTOs_MedicalSupplies_MedicalSupplyDto);

export type DeleteApiAppMedicalSupplyByIdMedicalSupplyData = {
    id: string;
};

export type DeleteApiAppMedicalSupplyByIdMedicalSupplyResponse = (unknown);

export type GetApiAppMedicalSupplyByIdMedicalSupplyData = {
    id: string;
};

export type GetApiAppMedicalSupplyByIdMedicalSupplyResponse = (Mediflow_DTOs_MedicalSupplies_MedicalSupplyDto);

export type PutApiAppMedicalSupplyByIdMedicalSupplyData = {
    id: string;
    requestBody?: Mediflow_DTOs_MedicalSupplies_CreateUpdateMedicalSupplyDto;
};

export type PutApiAppMedicalSupplyByIdMedicalSupplyResponse = (Mediflow_DTOs_MedicalSupplies_MedicalSupplyDto);

export type GetApiAppMedicalSupplyMedicalSupplyListResponse = (Volo_Abp_Application_Dtos_PagedResultDto_1);

export type PostApiAppMedicineMedicineData = {
    requestBody?: Mediflow_DTOs_Medicines_CreateUpdateMedicineDto;
};

export type PostApiAppMedicineMedicineResponse = (Mediflow_DTOs_Medicines_MedicineDto);

export type DeleteApiAppMedicineByIdMedicineData = {
    id: string;
};

export type DeleteApiAppMedicineByIdMedicineResponse = (unknown);

export type GetApiAppMedicineByIdMedicineData = {
    id: string;
};

export type GetApiAppMedicineByIdMedicineResponse = (Mediflow_DTOs_Medicines_MedicineDto);

export type PutApiAppMedicineByIdMedicineData = {
    id: string;
    requestBody?: Mediflow_DTOs_Medicines_CreateUpdateMedicineDto;
};

export type PutApiAppMedicineByIdMedicineResponse = (Mediflow_DTOs_Medicines_MedicineDto);

export type GetApiAppMedicineMedicineListResponse = (Volo_Abp_Application_Dtos_PagedResultDto_1);

export type GetApiAppPatientByIdPatientData = {
    id: string;
};

export type GetApiAppPatientByIdPatientResponse = (Mediflow_DTOs_Patient_PatientDto);

export type DeleteApiAppPatientByIdPatientData = {
    id: string;
};

export type DeleteApiAppPatientByIdPatientResponse = (unknown);

export type PutApiAppPatientByIdPatientData = {
    id: string;
    requestBody?: Mediflow_DTOs_Patient_PatientDto;
};

export type PutApiAppPatientByIdPatientResponse = (Mediflow_DTOs_Patient_PatientDto);

export type PostApiAppPatientPatientData = {
    requestBody?: Mediflow_DTOs_Patient_CreatePatientDto;
};

export type PostApiAppPatientPatientResponse = (Mediflow_DTOs_Patient_PatientDto);

export type GetApiAppPatientPatientsByNameOrNationalIdData = {
    input?: string;
};

export type GetApiAppPatientPatientsByNameOrNationalIdResponse = (Array<Mediflow_DTOs_Patient_PatientDto>);

export type GetApiAppPatientPatientsResponse = (Array<Mediflow_DTOs_Patient_PatientDto>);

export type GetApiAppPatientPatientListData = {
    maxResultCount?: number;
    searchValue?: string;
    skipCount?: number;
};

export type GetApiAppPatientPatientListResponse = (Volo_Abp_Application_Dtos_PagedResultDto_1);

export type PostApiAppPatientQueueEnqueuePatientData = {
    requestBody?: Mediflow_DTOs_PatientQueues_AddPatientQueueDto;
};

export type PostApiAppPatientQueueEnqueuePatientResponse = (Mediflow_DTOs_PatientQueues_PatientQueueDto);

export type PostApiAppPatientQueueByIdCompleteQueueData = {
    id: string;
};

export type PostApiAppPatientQueueByIdCompleteQueueResponse = (unknown);

export type PostApiAppPatientQueueByIdCancelQueueData = {
    id: string;
};

export type PostApiAppPatientQueueByIdCancelQueueResponse = (unknown);

export type GetApiAppPatientQueueLatestQueueNumberResponse = (number);

export type GetApiAppPatientQueuePatientQueuesData = {
    dateTime?: string;
};

export type GetApiAppPatientQueuePatientQueuesResponse = (Array<Mediflow_DTOs_PatientQueues_PatientQueueDto>);

export type PostApiAppPatientQueueByIdPrioritizeQueueData = {
    id: string;
};

export type PostApiAppPatientQueueByIdPrioritizeQueueResponse = (unknown);

export type PutApiAppPatientQueueByIdQueueStatusByDoctorIdData = {
    doctorId: string;
    id: string;
    status?: Mediflow_Entities_PatientQueues_QueueStatus;
};

export type PutApiAppPatientQueueByIdQueueStatusByDoctorIdResponse = (unknown);

export type PutApiAppPatientQueueQueueData = {
    requestBody?: Mediflow_DTOs_PatientQueues_PatientQueueDto;
};

export type PutApiAppPatientQueueQueueResponse = (Array<Mediflow_DTOs_PatientQueues_PatientQueueDto>);

export type GetApiAppPatientQueueByIdPatientQueueByIdForClerkData = {
    id: string;
};

export type GetApiAppPatientQueueByIdPatientQueueByIdForClerkResponse = (Mediflow_DTOs_PatientQueues_PatientQueueDto);

export type PostApiAppPatientQueueGenerateMcPdfData = {
    requestBody?: Mediflow_DTOs_PatientQueues_GenerateMcDto;
};

export type PostApiAppPatientQueueGenerateMcPdfResponse = ((Blob | File));

export type GetApiAppPatientQueueByIdLatestQueueData = {
    id: string;
};

export type GetApiAppPatientQueueByIdLatestQueueResponse = (Mediflow_DTOs_PatientQueues_PatientQueueDto);

export type GetApiAppPatientQueueLatestQueueForAllPatientsResponse = (Array<Mediflow_DTOs_PatientQueues_PatientQueueDto>);

export type GetApiAppPatientQueueQueuesForPatientByPatientIdData = {
    patientId: string;
};

export type GetApiAppPatientQueueQueuesForPatientByPatientIdResponse = (Array<Mediflow_DTOs_PatientQueues_PatientQueueWithNotesDto>);

export type PostApiAppPatientSessionEndPatientSessionBySessionIdData = {
    sessionId: string;
};

export type PostApiAppPatientSessionEndPatientSessionBySessionIdResponse = (unknown);

export type GetApiAppPatientSessionPatientSessionByPatientIdData = {
    patientId: string;
};

export type GetApiAppPatientSessionPatientSessionByPatientIdResponse = (Mediflow_DTOs_PatientSessions_PatientSessionDto);

export type GetApiAppPatientSessionQueueEntriesBySessionIdData = {
    sessionId: string;
};

export type GetApiAppPatientSessionQueueEntriesBySessionIdResponse = (Array<Mediflow_DTOs_PatientQueues_PatientQueueDto>);

export type GetApiAppPatientSessionLatestPatientSessionByPatientIdData = {
    patientId: string;
};

export type GetApiAppPatientSessionLatestPatientSessionByPatientIdResponse = (Mediflow_DTOs_PatientSessions_PatientSessionDto);

export type PostApiAppPaymentPaymentData = {
    requestBody?: Mediflow_DTOs_Payments_CreateUpdatePaymentDto;
};

export type PostApiAppPaymentPaymentResponse = (Mediflow_DTOs_Payments_PaymentDto);

export type PostApiAppPaymentPaymentsData = {
    requestBody?: Array<Mediflow_DTOs_Payments_CreateUpdatePaymentDto>;
};

export type PostApiAppPaymentPaymentsResponse = (unknown);

export type DeleteApiAppPaymentPaymentsData = {
    ids?: Array<(string)>;
};

export type DeleteApiAppPaymentPaymentsResponse = (unknown);

export type GetApiAppPaymentPaymentsResponse = (Array<Mediflow_DTOs_Payments_PaymentDto>);

export type DeleteApiAppPaymentByIdPaymentData = {
    id: string;
};

export type DeleteApiAppPaymentByIdPaymentResponse = (unknown);

export type GetApiAppPaymentByIdPaymentData = {
    id: string;
};

export type GetApiAppPaymentByIdPaymentResponse = (Mediflow_DTOs_Payments_PaymentDto);

export type PutApiAppPaymentByIdPaymentData = {
    id: string;
    requestBody?: Mediflow_DTOs_Payments_CreateUpdatePaymentDto;
};

export type PutApiAppPaymentByIdPaymentResponse = (Mediflow_DTOs_Payments_PaymentDto);

export type GetApiAppPaymentPaymentsByInvoiceIdByInvoiceIdData = {
    invoiceId: string;
};

export type GetApiAppPaymentPaymentsByInvoiceIdByInvoiceIdResponse = (Array<Mediflow_DTOs_Payments_PaymentDto>);

export type GetApiAppPaymentPaymentsByPatientIdByPatientIdData = {
    patientId: string;
};

export type GetApiAppPaymentPaymentsByPatientIdByPatientIdResponse = (Array<Mediflow_DTOs_Payments_PaymentDto>);

export type GetApiPermissionManagementPermissionsData = {
    providerKey?: string;
    providerName?: string;
};

export type GetApiPermissionManagementPermissionsResponse = (Volo_Abp_PermissionManagement_GetPermissionListResultDto);

export type PutApiPermissionManagementPermissionsData = {
    providerKey?: string;
    providerName?: string;
    requestBody?: Volo_Abp_PermissionManagement_UpdatePermissionsDto;
};

export type PutApiPermissionManagementPermissionsResponse = (unknown);

export type PostApiAppPrescriptionPrescriptionData = {
    requestBody?: Mediflow_DTOs_Prescriptions_CreateUpdatePrescriptionDto;
};

export type PostApiAppPrescriptionPrescriptionResponse = (Mediflow_DTOs_Prescriptions_PrescriptionDto);

export type PostApiAppPrescriptionPrescriptionsData = {
    requestBody?: Array<Mediflow_DTOs_Prescriptions_CreateUpdatePrescriptionDto>;
};

export type PostApiAppPrescriptionPrescriptionsResponse = (unknown);

export type DeleteApiAppPrescriptionPrescriptionsData = {
    ids?: Array<(string)>;
};

export type DeleteApiAppPrescriptionPrescriptionsResponse = (unknown);

export type GetApiAppPrescriptionPrescriptionsResponse = (Array<Mediflow_DTOs_Prescriptions_PrescriptionDto>);

export type DeleteApiAppPrescriptionByIdPrescriptionData = {
    id: string;
};

export type DeleteApiAppPrescriptionByIdPrescriptionResponse = (unknown);

export type GetApiAppPrescriptionByIdPrescriptionData = {
    id: string;
};

export type GetApiAppPrescriptionByIdPrescriptionResponse = (Mediflow_DTOs_Prescriptions_PrescriptionDto);

export type PutApiAppPrescriptionByIdPrescriptionData = {
    id: string;
    requestBody?: Mediflow_DTOs_Prescriptions_CreateUpdatePrescriptionDto;
};

export type PutApiAppPrescriptionByIdPrescriptionResponse = (Mediflow_DTOs_Prescriptions_PrescriptionDto);

export type GetApiAppPrescriptionPrescriptionsByMedicalHistoryIdsData = {
    medicalHistoryIds?: Array<(string)>;
};

export type GetApiAppPrescriptionPrescriptionsByMedicalHistoryIdsResponse = (Array<Mediflow_DTOs_Prescriptions_PrescriptionDto>);

export type GetApiAppPrescriptionPrescriptionsByPatientIdByPatientIdData = {
    patientId: string;
};

export type GetApiAppPrescriptionPrescriptionsByPatientIdByPatientIdResponse = (Array<Mediflow_DTOs_Prescriptions_PrescriptionDto>);

export type GetApiAppPrescriptionMedicalHistoryPrescriptionItemsByPrescriptionIdByPrescriptionIdData = {
    prescriptionId: string;
};

export type GetApiAppPrescriptionMedicalHistoryPrescriptionItemsByPrescriptionIdByPrescriptionIdResponse = (Array<Mediflow_DTOs_MedicalHistoryPrescriptionItems_MedicalHistoryPrescriptionItemDto>);

export type GetApiAccountMyProfileResponse = (Volo_Abp_Account_ProfileDto);

export type PutApiAccountMyProfileData = {
    requestBody?: Volo_Abp_Account_UpdateProfileDto;
};

export type PutApiAccountMyProfileResponse = (Volo_Abp_Account_ProfileDto);

export type PostApiAccountMyProfileChangePasswordData = {
    requestBody?: Volo_Abp_Account_ChangePasswordInput;
};

export type PostApiAccountMyProfileChangePasswordResponse = (unknown);

export type GetApiAppReportArAgingReportExcelResponse = ((Blob | File));

export type GetApiAppReportArAgingReportResponse = (Array<Mediflow_DTOs_Reports_AccountsReceivableAgingReportDto>);

export type GetApiAppReportDailyReportData = {
    date?: string;
};

export type GetApiAppReportDailyReportResponse = (Mediflow_DTOs_Reports_DailyReportDto);

export type GetApiAppReportDailyReportExcelData = {
    date?: string;
};

export type GetApiAppReportDailyReportExcelResponse = ((Blob | File));

export type GetApiIdentityRolesAllResponse = (Volo_Abp_Application_Dtos_ListResultDto_1);

export type GetApiIdentityRolesData = {
    filter?: string;
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiIdentityRolesResponse = (Volo_Abp_Application_Dtos_PagedResultDto_1);

export type PostApiIdentityRolesData = {
    requestBody?: Volo_Abp_Identity_IdentityRoleCreateDto;
};

export type PostApiIdentityRolesResponse = (Volo_Abp_Identity_IdentityRoleDto);

export type GetApiIdentityRolesByIdData = {
    id: string;
};

export type GetApiIdentityRolesByIdResponse = (Volo_Abp_Identity_IdentityRoleDto);

export type PutApiIdentityRolesByIdData = {
    id: string;
    requestBody?: Volo_Abp_Identity_IdentityRoleUpdateDto;
};

export type PutApiIdentityRolesByIdResponse = (Volo_Abp_Identity_IdentityRoleDto);

export type DeleteApiIdentityRolesByIdData = {
    id: string;
};

export type DeleteApiIdentityRolesByIdResponse = (unknown);

export type PostApiAppServiceProviderData = {
    requestBody?: Mediflow_DTOs_ServivceProviders_CreateServiceProviderDto;
};

export type PostApiAppServiceProviderResponse = (Mediflow_DTOs_ServivceProviders_CreatedServiceProviderDto);

export type GetApiAppServiceProviderResponse = (Array<Mediflow_DTOs_ServivceProviders_ServiceProviderListItemDto>);

export type DeleteApiAppServiceProviderByIdData = {
    id: string;
};

export type DeleteApiAppServiceProviderByIdResponse = (unknown);

export type GetApiAppServiceProviderByIdData = {
    id: string;
};

export type GetApiAppServiceProviderByIdResponse = (Mediflow_DTOs_ServivceProviders_ServiceProviderDto);

export type PutApiAppServiceProviderByIdData = {
    id: string;
    requestBody?: Mediflow_DTOs_ServivceProviders_CreateServiceProviderDto;
};

export type PutApiAppServiceProviderByIdResponse = (Mediflow_DTOs_ServivceProviders_CreatedServiceProviderDto);

export type GetApiAppServiceProviderServiceProviderForEditByTenantIdByTenantIdData = {
    tenantId: string;
};

export type GetApiAppServiceProviderServiceProviderForEditByTenantIdByTenantIdResponse = (Mediflow_DTOs_ServivceProviders_ServiceProviderDto);

export type PostApiAppServiceProviderByIdNewUpdateData = {
    id: string;
    requestBody?: Mediflow_DTOs_ServivceProviders_UpdateServiceProviderDto;
};

export type PostApiAppServiceProviderByIdNewUpdateResponse = (Mediflow_DTOs_ServivceProviders_CreatedServiceProviderDto);

export type GetApiAppServiceProviderNewShortIdData = {
    serviceProviderType?: Mediflow_Entities_ServiceProviders_ServiceProviderType;
};

export type GetApiAppServiceProviderNewShortIdResponse = (string);

export type GetApiAppServiceProviderByTypeData = {
    type?: Mediflow_Entities_ServiceProviders_ServiceProviderType;
};

export type GetApiAppServiceProviderByTypeResponse = (Array<Mediflow_DTOs_ServivceProviders_CreatedServiceProviderDto>);

export type PostApiAppServiceProviderByIdResetPasswordData = {
    id: string;
};

export type PostApiAppServiceProviderByIdResetPasswordResponse = (Mediflow_DTOs_ServivceProviders_CreatedServiceProviderDto);

export type GetApiAppStaffPermissionsResponse = (Mediflow_DTOs_Staffs_PermissionTreeNodeDto);

export type PostApiAppStaffAssignPermissionsToStaffByUserIdData = {
    requestBody?: Mediflow_DTOs_Staffs_PermissionAssignmentBatchDto;
    userId: string;
};

export type PostApiAppStaffAssignPermissionsToStaffByUserIdResponse = (unknown);

export type PostApiAppStaffStaffData = {
    requestBody?: Mediflow_DTOs_Staffs_CreateEditStaffDto;
};

export type PostApiAppStaffStaffResponse = (Mediflow_DTOs_Staffs_StaffDto);

export type GetApiAppStaffStaffResponse = (Array<Mediflow_DTOs_Staffs_StaffDto>);

export type PutApiAppStaffStaffByStaffIdData = {
    requestBody?: Mediflow_DTOs_Staffs_CreateEditStaffDto;
    staffId: string;
};

export type PutApiAppStaffStaffByStaffIdResponse = (unknown);

export type GetApiAppStaffStaffForEditByStaffIdData = {
    staffId: string;
};

export type GetApiAppStaffStaffForEditByStaffIdResponse = (Mediflow_DTOs_Staffs_CreateEditStaffDto);

export type GetApiAppStaffStaffListResponse = (Array<Mediflow_DTOs_Staffs_StaffListItemDto>);

export type GetApiMultiTenancyTenantsByIdData = {
    id: string;
};

export type GetApiMultiTenancyTenantsByIdResponse = (Volo_Abp_TenantManagement_TenantDto);

export type PutApiMultiTenancyTenantsByIdData = {
    id: string;
    requestBody?: Volo_Abp_TenantManagement_TenantUpdateDto;
};

export type PutApiMultiTenancyTenantsByIdResponse = (Volo_Abp_TenantManagement_TenantDto);

export type DeleteApiMultiTenancyTenantsByIdData = {
    id: string;
};

export type DeleteApiMultiTenancyTenantsByIdResponse = (unknown);

export type GetApiMultiTenancyTenantsData = {
    filter?: string;
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiMultiTenancyTenantsResponse = (Volo_Abp_Application_Dtos_PagedResultDto_1);

export type PostApiMultiTenancyTenantsData = {
    requestBody?: Volo_Abp_TenantManagement_TenantCreateDto;
};

export type PostApiMultiTenancyTenantsResponse = (Volo_Abp_TenantManagement_TenantDto);

export type GetApiMultiTenancyTenantsByIdDefaultConnectionStringData = {
    id: string;
};

export type GetApiMultiTenancyTenantsByIdDefaultConnectionStringResponse = (string);

export type PutApiMultiTenancyTenantsByIdDefaultConnectionStringData = {
    defaultConnectionString?: string;
    id: string;
};

export type PutApiMultiTenancyTenantsByIdDefaultConnectionStringResponse = (unknown);

export type DeleteApiMultiTenancyTenantsByIdDefaultConnectionStringData = {
    id: string;
};

export type DeleteApiMultiTenancyTenantsByIdDefaultConnectionStringResponse = (unknown);

export type GetApiSettingManagementTimezoneResponse = (string);

export type PostApiSettingManagementTimezoneData = {
    timezone?: string;
};

export type PostApiSettingManagementTimezoneResponse = (unknown);

export type GetApiSettingManagementTimezoneTimezonesResponse = (Array<Volo_Abp_NameValue>);

export type GetApiIdentityUsersByIdData = {
    id: string;
};

export type GetApiIdentityUsersByIdResponse = (Volo_Abp_Identity_IdentityUserDto);

export type PutApiIdentityUsersByIdData = {
    id: string;
    requestBody?: Volo_Abp_Identity_IdentityUserUpdateDto;
};

export type PutApiIdentityUsersByIdResponse = (Volo_Abp_Identity_IdentityUserDto);

export type DeleteApiIdentityUsersByIdData = {
    id: string;
};

export type DeleteApiIdentityUsersByIdResponse = (unknown);

export type GetApiIdentityUsersData = {
    filter?: string;
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiIdentityUsersResponse = (Volo_Abp_Application_Dtos_PagedResultDto_1);

export type PostApiIdentityUsersData = {
    requestBody?: Volo_Abp_Identity_IdentityUserCreateDto;
};

export type PostApiIdentityUsersResponse = (Volo_Abp_Identity_IdentityUserDto);

export type GetApiIdentityUsersByIdRolesData = {
    id: string;
};

export type GetApiIdentityUsersByIdRolesResponse = (Volo_Abp_Application_Dtos_ListResultDto_1);

export type PutApiIdentityUsersByIdRolesData = {
    id: string;
    requestBody?: Volo_Abp_Identity_IdentityUserUpdateRolesDto;
};

export type PutApiIdentityUsersByIdRolesResponse = (unknown);

export type GetApiIdentityUsersAssignableRolesResponse = (Volo_Abp_Application_Dtos_ListResultDto_1);

export type GetApiIdentityUsersByUsernameByUserNameData = {
    userName: string;
};

export type GetApiIdentityUsersByUsernameByUserNameResponse = (Volo_Abp_Identity_IdentityUserDto);

export type GetApiIdentityUsersByEmailByEmailData = {
    email: string;
};

export type GetApiIdentityUsersByEmailByEmailResponse = (Volo_Abp_Identity_IdentityUserDto);

export type GetApiIdentityUsersLookupByIdData = {
    id: string;
};

export type GetApiIdentityUsersLookupByIdResponse = (Volo_Abp_Users_UserData);

export type GetApiIdentityUsersLookupByUsernameByUserNameData = {
    userName: string;
};

export type GetApiIdentityUsersLookupByUsernameByUserNameResponse = (Volo_Abp_Users_UserData);

export type GetApiIdentityUsersLookupSearchData = {
    filter?: string;
    maxResultCount?: number;
    skipCount?: number;
    sorting?: string;
};

export type GetApiIdentityUsersLookupSearchResponse = (Volo_Abp_Application_Dtos_ListResultDto_1);

export type GetApiIdentityUsersLookupCountData = {
    filter?: string;
};

export type GetApiIdentityUsersLookupCountResponse = (number);

export type PostApiAppVisitTemplateVisitTemplateData = {
    requestBody?: Mediflow_DTOs_VisitTemplates_CreateUpdateVisitTemplateDto;
};

export type PostApiAppVisitTemplateVisitTemplateResponse = (Mediflow_DTOs_VisitTemplates_VisitTemplateDto);

export type DeleteApiAppVisitTemplateByIdVisitTemplateData = {
    id: string;
};

export type DeleteApiAppVisitTemplateByIdVisitTemplateResponse = (unknown);

export type GetApiAppVisitTemplateByIdVisitTemplateData = {
    id: string;
};

export type GetApiAppVisitTemplateByIdVisitTemplateResponse = (Mediflow_DTOs_VisitTemplates_VisitTemplateDto);

export type PutApiAppVisitTemplateByIdVisitTemplateData = {
    id: string;
    requestBody?: Mediflow_DTOs_VisitTemplates_CreateUpdateVisitTemplateDto;
};

export type PutApiAppVisitTemplateByIdVisitTemplateResponse = (Mediflow_DTOs_VisitTemplates_VisitTemplateDto);

export type GetApiAppVisitTemplateVisitTemplatesResponse = (Array<Mediflow_DTOs_VisitTemplates_VisitTemplateDto>);